In [1]:
import sklearn

In [2]:
import pandas as pd

In [3]:
import numpy as np

# Loadind Train and test Data

In [9]:
train = pd.read_csv('csv_files/train_data.csv')
test = pd.read_csv('csv_files/test_data.csv')

In [10]:
train.head()

Unnamed: 0           0           1          2          3          4  \
0           0 -278.576206  129.164773 -22.060418  -4.741548 -26.047579   
1           1 -342.095304  205.723661   9.098802  30.607301 -16.494442   
2           2 -273.695426  172.579899 -43.313463 -17.121503 -15.582635   
3           3 -266.503106  161.376292 -41.794887  -5.719112 -34.077310   
4           4 -478.196607  143.358287  27.101666  18.975435  -3.183125   

           5          6          7          8  ...       167        168  \
0 -45.005509  18.134263  24.779084 -13.573361  ... -0.067562  58.970386   
1  -7.834917  -3.111534  23.628277  19.313014  ...  0.478289  47.473347   
2   8.129898 -13.048666  36.253019 -11.318930  ... -0.715795  57.436906   
3  -7.891926  -4.983601  31.810949  -2.764222  ... -0.745457  45.201427   
4  11.197189  17.749401  12.999041   1.289795  ... -0.702559  38.972669   

        169          170         171       172          173          174  \
0  3.660203  2045.457124  284.404937  3.436525  3679.102095  1602.865979   
1  5.557124  1237.889692  482.724273  3.641655  3431.431322   881.644303   
2  8.583013  1182.182189  528.375530  2.949788  3449.076681   895.988554   
3  9.795621  1225.329185  417.279402  4.129218  3413.659723   961.256659   
4  8.022097  1936.711883  421.736763  1.942523  3323.223352  1419.775724   

                                            filepath  label  
0  TrainingDataset/Functionaldysphonia/wavefile/0...      0  
1  TrainingDataset/Functionaldysphonia/wavefile/0...      0  
2  TrainingDataset/Functionaldysphonia/wavefile/0...      0  
3  TrainingDataset/Functionaldysphonia/wavefile/0...      0  
4  TrainingDataset/Functionaldysphonia/wavefile/0...      0  

[5 rows x 178 columns]

In [11]:
X_train = train.drop(['filepath', 'label'], axis=1)
X_test = test.drop(['filepath', 'label'], axis = 1)
y_train = train['label']
y_test = test['label']

# Training

In [7]:
from sklearn.svm import SVC

In [8]:
model = SVC(C=1, kernel='rbf', gamma=0.001)

In [12]:
model.fit(X_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
predictions = model.predict(X_test)

In [14]:
from sklearn.metrics import classification_report

In [16]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.38      0.30      0.33        10
           1       0.50      0.30      0.37        10
           2       0.27      0.70      0.39        10
           3       0.00      0.00      0.00        10

   micro avg       0.33      0.33      0.33        40
   macro avg       0.29      0.32      0.27        40
weighted avg       0.29      0.33      0.27        40



In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
print(confusion_matrix(y_test, predictions))

[[3 0 7 0]
 [2 3 5 0]
 [2 1 7 0]
 [1 2 7 0]]


# Cross validation

In [19]:
from sklearn.model_selection import cross_val_score

In [22]:
model = SVC(C=1, kernel='rbf', gamma=0.001)

In [23]:
scores = cross_val_score(model,X_train, y_train, cv = 10)
print("Cross-validation scores: {}".format(scores))

Cross-validation scores: [0.5    0.4375 0.5    0.625  0.5    0.4375 0.375  0.1875 0.4375 0.375 ]


# Grid Search to find optimal parameters

In [24]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}

In [26]:
from sklearn.model_selection import GridSearchCV

In [27]:
grid_search = GridSearchCV(SVC(), param_grid, cv=3)

In [28]:
grid_search.fit(X_train, y_train)

/home/kevindegila/.conda/envs/deep-learning/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100], 'gamma': [0.001, 0.01, 0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [29]:
print("Test set score: {:.2f}".format(grid_search.score(X_test, y_test)))

Test set score: 0.40
